import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap/dist/js/bootstrap";
import { render, router } from "./utilities";
import HomePage from "./components/HomePage";
import NotFound from "./pages/NotFound";
import Search from "./components/Search";
import ProductDetail from "./components/ProductDetail";
const app = document.querySelector("#app");
router.on("/", () => render(HomePage, app));
router.on("/product/:id", ({ data }) => render(() => ProductDetail(data), app));
router.on("/search", () => render(Search, app));
router.notFound(() => render(NotFound, app));
router.resolve();
